#Require Node.js12 minimum
# FROM artifactory.dsto.defence.gov.au/docker-dsop-prn-local/dsop/nodejs20
FROM artifactory.dsto.defence.gov.au/docker-aire-local/ubi9-nodejs20-chromium:d045f7f4-73286

# The base image sets USER node and WORKDIR /home/node
# USER node

# Need to swich back to ROOT to install more stuff
USER 0

# RUN apt-get update \
#  && apt-get install -y chromium \
#     fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
#     --no-install-recommends

# chromium \
# error: No package matches 'chromium'
# no match:
# fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf \
# libxss1 \
# gconf-service \
# libasound2 \
# libatk1.0-0 \
# libc6 \
# libcairo2 \
# libcups2 \
# libdbus-1-3 \
# libexpat1 \
# libfontconfig1 \
# libgcc1 \
# libgconf-2-4 \
# libgdk-pixbuf2.0-0 \
# libglib2.0-0 \
# libgtk-3-0 \
# libnspr4 \
# libpango-1.0-0 \
# libpangocairo-1.0-0 \
# libstdc++6 \
# libx11-6 \
# libx11-xcb1 \
# libxcb1 \
# libxcomposite1 \
# libxcursor1 \
# libxdamage1 \
# libxext6 \
# libxfixes3 \
# libxi6 \
# libxrandr2 \
# libxrender1 \
# libxss1 \
# libxtst6 \
# fonts-liberation \
# libappindicator1 \
# libnss3 \
# xdg-utils \
# libgbm-dev \
# libxcb-dri3-0

RUN dnf upgrade -y && \
    dnf install -y \
      ca-certificates \
      lsb-release \
      wget \
# Why is the following required?
RUN cp /usr/bin/chromium /usr/bin/chromium-browser

# Create app directory
WORKDIR /usr/src/app

# Change the ownership of /usr/src/app to the `node` user
RUN chown -R node:node /usr/src/app

# Switch USER back from root to node
USER node

# Bundle app source
COPY . .


ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
ENV PUPPETEER_EXECUTABLE_PATH /usr/bin/chromium

#Install deps
# RUN npm install && apt-get update && apt-get install -y gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget libgbm-dev libxcb-dri3-0
RUN npm install

EXPOSE 3000
CMD node ./index.js -r . --oc 1
